#!/usr/bin/env bash
cd ./app/
npm i sudo npm install scrypt --save --unsafe-perm=true --allow-root
cd node_modules/scrypt
sudo node-gyp configure
sudo node-gyp rebuild --target=1.8.2 --arch=x64 --dist-url=https://atom.io/download/atom-shell